{{- if and .Values.traefik.enabled .Values.traefik.https.enabled  }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "nginx-echo-headers.fullname" . }}
spec:
  # Secret names are always required.
  secretName: {{ include "nginx-echo-headers.fullname" . }}
  # Hard limit set by Let's Encrypt, non changeable
  duration: {{ .Values.traefik.https.certificate.duration }}
  renewBefore: {{ .Values.traefik.https.certificate.renewBefore }}
  subject:
    organizations:
      {{- range .Values.traefik.https.certificate.organizations }}
      - {{ . }}
      {{- end }}
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
      {{- range .Values.traefik.dnsNames }}
      - {{ . }}
      {{- end }}
  # Issuer references are always required.
  issuerRef:
    name: {{ .Values.traefik.https.certificate.issuer.name }}
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: {{ .Values.traefik.https.certificate.issuer.kind | default "Issuer" }}
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: {{ .Values.traefik.https.certificate.issuer.group | default "cert-manager.io" }}
{{- end }}
