{{- if and (.Values.argoRollout.canary.enabled) (.Values.traefik.enabled)  }}
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: {{ include "nginx-echo-headers.fullname" . }}
spec:
  {{- if not .Values.argoRollout.canary.mirror }}
  weighted:
    services:
    - name: {{ include "nginx-echo-headers.fullname" . }} # k8s service name that you need to create for stable application version
      port: {{ .Values.service.port }}
    - name: {{ include "nginx-echo-headers.fullname" . }}-canary # k8s service name that you need to create for new application version
      port: {{ .Values.service.port }}
  {{- else }}
  mirroring:
    name: some-service
    port: {{ .Values.service.port }}
    mirrors:
    - name: {{ include "nginx-echo-headers.fullname" . }} # k8s service name that you need to create for stable application version
      port: {{ .Values.service.port }}
    - name: {{ include "nginx-echo-headers.fullname" . }}-canary # k8s service name that you need to create for new application version
      port: {{ .Values.service.port }}
  {{- end }}
{{- end }}