{{- $httpsEnabled := .Values.ingress.https.enabled -}}
{{- $fullname := include "nginx-echo-headers.fullname" . -}}
{{- $serviceName := include "nginx-echo-headers.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $middlewares := .Values.ingress.https.middlewares -}}
{{- $releaseNamespace := .Release.Namespace }}

{{- if and (.Values.ingress.enabled) (.Values.ingress.traefik.enabled) }}
{{- if $httpsEnabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "nginx-echo-headers.fullname" . }}-https
spec:
  entryPoints:
  - websecure
  routes:
  {{- range .Values.ingress.hosts }}
  - kind: Rule
    match: Host(`{{ .name }}`)
    priority: 10
    services:
    - name: {{ default $serviceName .service }}
      port: {{ default $servicePort .servicePort }}
  {{- end }}
  tls:
    secretName: {{ include "nginx-echo-headers.fullname" . }}
{{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "nginx-echo-headers.fullname" . }}-http
spec:
  entryPoints:
    - web
  routes:
  {{- range .Values.ingress.hosts }}
  - kind: Rule
    match: Host(`{{ .name }}`)
    priority: 10
    services:
    - name: {{ default $serviceName .service }}
      port: {{ default $servicePort .servicePort }}
    {{- if  $httpsEnabled }}
    middlewares:
    {{-  range $middlewares }}
    - name: {{ .name }}
      namespace: {{ .namespace | default $releaseNamespace }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
